### ISSUE TITLE
Text in "About" page has bad contrast

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/flybywiresim-website#1]
The contrast on the text shown in the screenshot is not high enough.

![image](https://user-images.githubusercontent.com/4503241/92280260-06e82080-eec7-11ea-8a2e-09c6dbc6c0f4.png)

**Comment by UncleClapton** [comment]
This is happening because the font that is supposed to be displaying cannot be loaded from google fonts. Website needs to be served over HTTPs for the font data to be loaded from google.

**Comment by NathanInnes** [comment]
Solved.
