### ISSUE TITLE
[REQUEST]  Show runway on the navigation display

### ISSUE THREAD

**Issue by andyalex03** [flybywiresim/flybywiresim-website#34]
![EA8952DD-F7B3-453F-A122-3B01A348DF3F](https://user-images.githubusercontent.com/76818907/103416746-fa629480-4b55-11eb-82e0-29bbeb68191a.jpeg)
![3C106177-9B1D-4E68-8ED3-442FAD492916](https://user-images.githubusercontent.com/76818907/103416748-fc2c5800-4b55-11eb-8ccb-0d953ec24bfd.jpeg)

**Comment by NathanInnes** [comment]
You have made this request on the wrong repository. Issues related to the website should be posted here and if you have issues/requests about the aircraft please send them to the A32NX repository instead.
