### ISSUE TITLE
Problems with react-changelog

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/flybywiresim-website#6]
`react-changelog` uses deprecated lifecycle methods and improperly handles rendered arrays. It doesn't seem like it's being actively maintained, either.

Would there be any interest in replacing this with a new library or even something built specifically for this project?

I'm needing a changelog page in one of my other projects so I'd be able to build a replacement lib that would work for the both of us.

**Comment by NathanInnes** [comment]
Closing due to a revamp of entire site is underway <3 miss u
